version: '3.8'
services:
  db:
    container_name: flom-react_prod_db
    image: library/postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: ${PASSWORD}
      POSTGRES_DB: flom
    env_file:
      - ./.env
    restart: always
    volumes:
      - ./db/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
      - ./data:/var/lib/postgresql/data
  server:
    container_name: flom-react_prod_server
    build:
      context: ./server
      dockerfile: Dockerfile
    volumes:
      - /app/node_modules
    ports:
      - "3001:3001"
    environment:
      DB_PASSWORD: ${PASSWORD}
      NODE_ENV: production
    env_file:
      - ./.env
    restart: always
    depends_on:
      - db
  client:
    container_name: flom-react_prod_client
    build:
      context: ./client
      dockerfile: Dockerfile
    volumes:
      - /app/node_modules
    restart: always
    ports:
      - "8080:80"
    depends_on:
      - db
      - server
