version: '3.8'
services:
  db:
    container_name: flom_db
    image: library/postgres
    ports:
      - "5432:5432"
    env_file:
      - ./.env
    environment:
      POSTGRES_PASSWORD: ${PASSWORD}
      POSTGRES_DB: flom
    restart: always
    volumes:
      - ./db:/docker-entrypoint-initdb.d
      - ./data:/var/lib/postgresql/data
  server:
    container_name: flom_server
    build:
      context: ./server
      dockerfile: Dockerfile
    volumes:
      - ./secret:/app/secret
    ports:
      - "3001:3001"
    env_file:
      - ./.env
    environment:
      DB_PASSWORD: ${PASSWORD}
      NODE_ENV: production
    restart: always
    depends_on:
      - db
  client:
    container_name: flom_client
    build:
      context: ./client
      dockerfile: Dockerfile
    restart: always
    ports:
      - "80:80"
    depends_on:
      - db
      - server