version: '3.8'
services:
  db:
    container_name: flom-react_dev_db
    image: library/postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: flom
    restart: always
    volumes:
      - ./db:/docker-entrypoint-initdb.d/
  server:
    container_name: flom-react_dev_server
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - ./server:/app
    ports:
      - "3001:3001"
    depends_on:
      - db
  client:
    container_name: flom-react_dev_client
    stdin_open: true
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - ./client:/app
    ports:
      - "3000:3000"
    depends_on:
      - db
      - server
