export { default as DashboardPage } from './DashboardPage';
export { default as HomePage } from './HomePage';
export { default as LoginPage } from './LoginPage';
export { default as MapPage } from '../components/MapRender';
export { default as Survey } from './Survey';
export { default as SurveyDetailPage } from './SurveyDetailPage';
export { default as SurveyResponsePage } from './SurveyResponsePage';
export { default as SurveyListPage } from './SurveyListPage';
export { default as SurveyAddPage } from './SurveyAddPage';