FROM node:lts-alpine as build

EXPOSE 3001

WORKDIR /app

COPY package.json yarn.lock .yarn ./

RUN yarn set version berry

RUN yarn install --immutable --network-timeout 1000000

COPY . ./

CMD ["yarn", "start:dev"]
